config/routes.rb
Rails.application.routes.draw do
  resources :customer_bookings
  root 'home#home'
  get 'contact', to: 'home#contact'
  get 'about', to: 'home#about'

  post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer_booking.rb
class CustomerBooking < ApplicationRecord
  # required fields
  validates :name, :email, :phoneNumber, presence: true
  # ensures only numbers are enter in the phone number
  validates :phoneNumber, numericality: { only_integer: true } 
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/customer_bookings_controller.rb
class CustomerBookingsController < ApplicationController
  before_action :set_customer_booking, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:index]
  # GET /customer_bookings
  # GET /customer_bookings.json
  def index
    @customer_bookings = CustomerBooking.all
  end

  # GET /customer_bookings/1
  # GET /customer_bookings/1.json
  def show
  end

  # GET /customer_bookings/new
  def new
    @customer_booking = CustomerBooking.new
  end

  # GET /customer_bookings/1/edit
  def edit
  end

  # POST /customer_bookings
  # POST /customer_bookings.json
  def create
    @customer_booking = CustomerBooking.new(customer_booking_params)

    respond_to do |format|
      if @customer_booking.save
        format.html { redirect_to @customer_booking, notice: 'Customer booking was successfully created.' }
        format.json { render :show, status: :created, location: @customer_booking }
      else
        format.html { render :new }
        format.json { render json: @customer_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_bookings/1
  # PATCH/PUT /customer_bookings/1.json
  def update
    respond_to do |format|
      if @customer_booking.update(customer_booking_params)
        format.html { redirect_to @customer_booking, notice: 'Customer booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_booking }
      else
        format.html { render :edit }
        format.json { render json: @customer_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_bookings/1
  # DELETE /customer_bookings/1.json
  def destroy
    @customer_booking.destroy
    respond_to do |format|
      format.html { redirect_to customer_bookings_url, notice: 'Customer booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_booking
      @customer_booking = CustomerBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_booking_params
      params.require(:customer_booking).permit(:name, :email, :children, :phoneNumber)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def contact
  end

  def about
  end


  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else if name.blank?
      flash[:alert] = I18n.t('home.request_contact.no_name')
    else if message.blank?
      flash[:alert] = I18n.t('home.request_contact.no_message')
    end
      # Send an email
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    #todo - redirect to thank you page with link to root_path
    redirect_to root_path
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_bookings_helper.rb
module CustomerBookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customer_bookings/_form.html.erb
<%= form_for @customer_booking do |f| %>
  <% if @customer_booking.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@customer_booking.errors.count, "error")} prohibited this customer_booking from being saved:" %>
      </h2>
      <ul>
        <% @customer_booking.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
  <center>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :children %>
    <%= f.number_field :children %>
  </div>
  <div class="field">
    <%= f.label :Phone_Number %>
    <%= f.number_field :phoneNumber %>
  </div>

  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
</center>
</div>
<% end %>

app/views/customer_bookings/edit.html.haml
%h1 Edit customer_booking

= render 'form'

= link_to 'Show', @customer_booking
\|
= link_to 'Back', customer_bookings_path

app/views/customer_bookings/index.html.erb
<h1>Customer Bookings</h1>
<table class="table table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Children</th>
      <th>Phonenumber</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @customer_bookings.each do |customer_booking| %>
      <tr>
        <td>
          <%= customer_booking.name %>
        </td>
        <td>
          <%= customer_booking.email %>
        </td>
        <td>
          <%= customer_booking.children %>
        </td>
        <td>
          <%= customer_booking.phoneNumber %>
        </td>
        <td>
          <%= link_to 'Show', customer_booking %>
        </td>
        <td>
          <%= link_to 'Edit', edit_customer_booking_path(customer_booking) %>
        </td>
        <td>
          <%= link_to 'Destroy', customer_booking, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Customer booking', new_customer_booking_path %>

app/views/customer_bookings/new.html.erb
<div class="container-fluid">
  <div class="row">

  <center>  <h1>New Booking</h1>
  </center>

</div>
</div>
<%= render 'form' %>

app/views/customer_bookings/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @customer_booking.name
%p
  %b Email:
  = @customer_booking.email
%p
  %b Children:
  = @customer_booking.children
%p
  %b Phonenumber:
  = @customer_booking.phoneNumber

= link_to 'Edit', edit_customer_booking_path(@customer_booking)
\|
= link_to 'Back', customer_bookings_path

app/views/home/about.html.erb
<div class="container-fluid" >
   <div class="text-center">
      <h2 style="font-size: 50px">Our Story</h2>
   </div>
   <div class="row">
      <div class="col-sm-8" >
         <!-- locale text -->
         <h4>
            <%= t('.welcome') %>
         </h4>
         <br>
         <p>  <%= t('.moreText') %></p>
      </div>
      <div class="col-sm-4" style="padding-top: 22px;">
         <img src="assets/Child1.jpg" class="img-thumbnail" alt="Family" style="width:100%;box-shadow: 10px 15px 15px 0px rgba(0, 0, 0, 0.2), 0 8px 20px 0 rgba(0, 0, 0, 0.19);">
      </div>
   </div>
</div>
<div class="container-fluid text-center" style="background-color: #FFFF00; padding-top: 25pt;">
   <h2><%= t('.services')%></h2>
   <h4><%= t('.servicesDescription')%></h4>
   <br>
   <div class="row">
      <div class="col-sm-4">
         <i class="far fa-clock fa-5x"></i>
         <h3><%= t('.time')%></h3>
         <p><%= t('.timeDescription')%></p>
      </div>
      <div class="col-sm-4">
         <i class="fa fa-coffee fa-5x"></i>
         <h3><%= t('.Cafe')%></h3>
         <p><%= t('.cafeDescription')%></p>
      </div>
      <div class="col-sm-4">
         <i class="fa fa-lock fa-5x"></i>
         <h3><%= t('.secure')%></h3>
         <p><%= t('.secureDescription')%></p>
      </div>
   </div>
   <br><br>
   <div class="row">
      <div class="col-sm-4">
         <i class="fa fa-wheelchair fa-5x"></i>
         <h3><%= t('.accessibility')%></h3>
         <p><%= t('.accessibilityDescription')%></p>
      </div>
      <div class="col-sm-4">
         <i class="fa fa-birthday-cake fa-5x"></i>
         <h3><%= t('.parties')%></h3>
         <p><%= t('.partiesDescription')%><br/> <%= t('.PartyPackages')%></p>
      </div>
      <div class="col-sm-4">
         <i class="fas fa-bus fa-5x"></i>
         <h3><%= t('.play')%></h3>
         <p><%= t('.playDescription')%></p>
      </div>
   </div>
</div>

app/views/home/contact.html.erb
<!-- <script>
   function RequireField() {
       alert("Email address required");
   } -->
</script>
<body>
   <div class="container-fluid">
      <center>
         <h1>
            <%= t('.title') %>
         </h1>
         <p>
            <%= t('.contact_us') %>
         </p>
      </center>
      <div class="row">
         <div class="col-md-2 col-md-offset-1">
            <%= form_tag request_contact_path, method: 'post' do %>
            <%= label_tag :name, t('.name') %>
            <%= text_field_tag :name, '', title: t('.enter_name'), size: 50 %>
            <%= label_tag :email, t('.email')%>
            <%= email_field_tag :email,'', title: t('.enter_email'), size: 50 %>
            <%= label_tag :telephone, t('.telephone') %>
            <%= telephone_field_tag :telephone, '', title: t('.enter_telephone'), size: 50 %>
            <%= label_tag :message, t('.message') %>
            <%= text_field_tag :message, '', title: t('.enter_message'), size: 50 %>
            <%= check_box_tag(:send_email) %>
            <%= label_tag(:send_email, "Send me email receipt") %>
            <br>
              <p>we will attempt to reply to our emails within 3 business days.</p>
            <%= submit_tag t('.submit') %>
            <% end %>
         </div>
      </div>
   </div>
</body>

app/views/home/home.html.erb
<body>
   <!-- <div class="jumbotron text-center">
      <h1>
        <%= t('.title') %>
      </h1>
      <p>
        <%= t('.welcome') %>
      </p>
      </div> -->
   <div class="container-fluid"
      style="background-image: url(assets/Background2.png);background-size: 1500px 1200px; ">
      <div class="row">
         <center>
            <div class="col-sm-6">
               <div class="logoRotate">
                  <img id="logo" src="assets/LogoFull.png" class="logoFront" alt="Little Big Town">
               </div>
            </div>
            <div class="col-sm-6" style="font-weight: 700">
               <div class="text-center" style="width: 100%; padding-top: 50px">
                  <h1><%= t('.tidworth')%></h1>
                  <img src="assets/Giraffe2.png"  class="giraffe" alt="Giraffe">
               </div>
            </div>
         </center>
      </div>
   </div>
   <div class="container-fluid" style="padding-top: 25pt">
      <div class="row">
         <div class="col-sm-8">
            <h2><%= t('.welcome')%></h2>
            <h4><%= t('.role')%></h4>
            <a href="about" class="btn btn-info" role="button">About...</a>
         </div>
         <div class="col-sm-4">
            <img src="assets/Family.jpg"   class="img-thumbnail" alt="Family" style="width:90%; box-shadow: 10px 15px 15px 0px rgba(0, 0, 0, 0.2), 0 8px 20px 0 rgba(0, 0, 0, 0.19);">
         </div>
      </div>
   </div>
   <div class="container-fluid" style="background-color: #FFFF00;">
      <div class="row">
         <div class="col-sm-4">
            <img src="assets/Event.jpg" class="img-thumbnail" alt="Event">
         </div>
         <div class="col-sm-8">
            <h2><%= t('.events')%></h2>
            <h4><%= t('.eventsDescription')%></h4>
            <a href="Events.html" class="btn btn-info" role="button">More...</a>
         </div>
      </div>
   </div>
   <div class="container-fluid" style="padding-top: 25pt; background-color: #89cff0">
      <div class="row">
         <div class="col-sm-8">
            <h2><%= t('.parties')%></h2>
            <h4><%= t('.partiesDescription')%></h4>
            <a href="#" class="btn btn-info" role="button">Coming Soon</a>
         </div>
         <div class="col-sm-4">
            <img src="assets/Party.jpg" class="img-thumbnail" alt="Party">
         </div>
      </div>
   </div>
   <div class="container-fluid">
      <div class="row">
         <div class="col-sm-4">
            <img src="assets/PayOnline.png" class="img-thumbnail" alt="Family" style="box-shadow: 10px 15px 15px 0px rgba(0, 0, 0, 0.2), 0 8px 20px 0 rgba(0, 0, 0, 0.19);">
         </div>
         <div class="col-sm-8">
            <h2><%= t('.Book')%></h2>
            <h4><%= t('.BookDescription')%></h4>
            <a href="customer_bookings/new" class="btn btn-info" role="button">Book now</a>
         </div>
      </div>
   </div>
</body>

app/views/layouts/application.html.erb
<!-- !!!

-# <link rel="stylesheet" href="CSS/footer.css"/>
-# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
-# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>
-# <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Open+Sans+Condensed:300" rel="stylesheet">
-# <link rel="icon" href="Images/LogoFull.png" type="image/x-icon" />
-# <link rel="shortcut icon" href="Images/LogoFull.png" type="image/x-icon" />
-# <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
-# <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
-# <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script> -->


<html>
  <head>
    <meta charset="utf-8"/>
    <meta content="ie=edge" http-equiv="x-ua-compatible"/>
    <title>
      <%= t('app_title') %>
    </title
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'modernizr' %>
    <%= csrf_meta_tags %>
  </head>
  <body></body>
</html>
<% if signed_in? %>
  currently signed in: <% current_user.email %>
    <%= link_to 'Sign out', sign_out_path, method: :delete %>

<% end %>
<% # - else %>
<% #   = link_to 'Sign in', sign_in_path %>
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>">
      <%= value %>
    </div>
  <% end %>

<!-- bootstrap conttainer-fluid to be suitable for a variety of screen sizes -->
  <div class="container-fluid">
  <%= render 'shared/header' %>
  <% flash.each do |key, value| %>
    <%= content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank? %>
  <% end %>

  <%= yield %>
  <%= render 'shared/footer' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- head should be in applicaiton.html.haml -->
<head>
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>
   <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</head>
<footer>
   <div class="w3-container w3-padding-32 w3-black w3-center w3-xsmall">
      <hr>
      <div class="container-fluid">
         <div class="row">
            <div class="col-xs-12 col-sm-4 col-lg-4">
               <div class="image"><i class="fa fa-envelope fa-3x" aria-hidden="true"></i></div>
               <div>
                  <h3 style="font-size: 35px">Contact</h3>
                  <p>
                     <i class="fas fa-envelope" aria-hidden="true"></i> &nbsp <a href="mailto:test@test.com?Subject=%20Web_Query" target="_top">help@LittleBigTown.co.uk</a>
                     <br>
                     <br>
                     <i class="fas fa-phone" aria-hidden="true"></i> &nbsp (01980)-849407
                     <br>
                  </p>
               </div>
            </div>
            <div class="col-xs-12 col-sm-4 col-lg-4">
               <div class="image"><i class="fas fa-map-marker-alt fa-3x"></i></div>
               <h3 class="title" style="font-size: 35px">Location</h3>
               <p>
                  <i class="fas fa-map-marker-alt"></i> &nbsp Unit B - Arch House,
                  <br> Pennings Road,
                  <br> South Tidworth,
                  <br> Wiltshire
                  <br><small>(Next door to the Spar)</small>
               </p>
            </div>
            <div class="col-xs-12 col-sm-4 col-lg-4">
               <div class="image"><i class="far fa-clock fa-3x" aria-hidden="true"></i></div>
               <h3 class="title" style="font-size: 35px">Opening Times</h3>
               <div class="row" style="padding-top: 5px">
                  <div class="col-sm-12">
                     <p><b>Mon - Sat</b>
                        <br>
                        09:30 - 16:00
                     </P>
                  </div>
               </div>
               <div class="row">
                  <div class= "col-sm-12">
                     <p><b>Sun</b>
                        <br>
                        (By Appointment Only)
                     </p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <p>&copy; Matt Godfrey</p>
</footer>

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-expand-lg.navbar-light.bg-light
  .containter-fluid
    .navbar-header
      //%img{:alt => "logo", :src => "/assets/LogoFull.png"}
      %button.navbar-toggle.collapsed{ type: :button, 'data-toggle' => :collapse,
                      'data-target' => "#bootstrap_minimise" }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar


      = link_to 'LittleBigTown', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse#bootstrap_minimise
      %ul.nav.navbar-nav.navbar-right
        %li.active= link_to 'About', about_path
        %li.active= link_to 'Contact', contact_path
        %li.active= link_to 'Book', new_customer_booking_path
        %li.active= link_to 'Admin', customer_bookings_path